/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 08-pro-2024 22:05:45 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Adresa_Region]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Adresa] DROP CONSTRAINT [FK_Adresa_Region]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Klient_Adresa]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_Adresa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Objednavka_Adresa_D]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Objednavka] DROP CONSTRAINT [FK_Objednavka_Adresa_D]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Objednavka_Klient]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Objednavka] DROP CONSTRAINT [FK_Objednavka_Klient]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Objednavka_Zamestnanec]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Objednavka] DROP CONSTRAINT [FK_Objednavka_Zamestnanec]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Objednavka_Adresa_F]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Objednavka] DROP CONSTRAINT [FK_Objednavka_Adresa_F]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RadekObjednavky_Zbozi]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [RadekObjednavky] DROP CONSTRAINT [FK_RadekObjednavky_Zbozi]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_RadekObjednavky_Objednavka]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [RadekObjednavky] DROP CONSTRAINT [FK_RadekObjednavky_Objednavka]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Sklad_Adresa]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Sklad] DROP CONSTRAINT [FK_Sklad_Adresa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zamestnanec_Oddeleni]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zamestnanec] DROP CONSTRAINT [FK_Zamestnanec_Oddeleni]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zbozi_ProduktovaRada]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zbozi] DROP CONSTRAINT [FK_Zbozi_ProduktovaRada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zbozi_Sklad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zbozi] DROP CONSTRAINT [FK_Zbozi_Sklad]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Adresa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Adresa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Klient]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Klient]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Objednavka]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Objednavka]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Oddeleni]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Oddeleni]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ProduktovaRada]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ProduktovaRada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[RadekObjednavky]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [RadekObjednavky]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Region]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Region]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Sklad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Sklad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Zamestnanec]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Zamestnanec]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Zbozi]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Zbozi]
GO

/* Create Tables */

CREATE TABLE [Adresa]
(
	[AdresaID] int IDENTITY(1,1) NOT NULL,
	[RegionID] int NOT NULL,
	[Ulice] varchar(50) NOT NULL,
	[CisloPopisne] int NOT NULL,
	[Vchod] varchar(5) NULL,
	[PSC] varchar(15) NOT NULL,
	[Mesto] varchar(60) NOT NULL,
	[Zeme] varchar(50) NOT NULL
)
GO

CREATE TABLE [Klient]
(
	[KlientID] int IDENTITY(1,1) NOT NULL,
	[AdresaID] int NOT NULL,
	[Titul] varchar(20) NULL,
	[Jmeno] varchar(100) NOT NULL,
	[Prijmeni] varchar(100) NOT NULL,
	[Email] varchar(50) NOT NULL,
	[TelefonniCislo] varchar(30) NULL,
	[Prostredky] money NOT NULL,
	[ObecnePripominky] varchar(100) NULL
)
GO

CREATE TABLE [Objednavka]
(
	[ObjednavkaID] int IDENTITY(1,1) NOT NULL,
	[KlientID] int NOT NULL,
	[FakturacniAdresa] int NOT NULL,
	[DodaciAdresa] int NOT NULL,
	[ZamestnanecID] int NOT NULL,
	[Cena] int NOT NULL,
	[Mena] varchar(20) NOT NULL,
	[DatumOdeslani] datetime NULL,
	[DatumDoruceni] datetime NULL,
	[Platba] varchar(20) NOT NULL,
	[Pripominka] varchar(100) NULL
)
GO

CREATE TABLE [Oddeleni]
(
	[OddeleniID] int IDENTITY(1,1) NOT NULL,
	[Nazev] varchar(30) NOT NULL,
	[Email] varchar(30) NOT NULL,
	[TelefonniCislo] varchar(30) NULL,
	[Fax] varchar(30) NULL
)
GO

CREATE TABLE [ProduktovaRada]
(
	[ProduktovaRadaID] int IDENTITY(1,1) NOT NULL,
	[Nazev] varchar(30) NOT NULL,
	[RokUvedeni] date NOT NULL
)
GO

CREATE TABLE [RadekObjednavky]
(
	[RadekObjednavkyID] int IDENTITY(1,1) NOT NULL,
	[ObjednavkaID] int NOT NULL,
	[ZboziID] int NOT NULL,
	[Mnozstvi] int NOT NULL
)
GO

CREATE TABLE [Region]
(
	[RegionID] int IDENTITY(1,1) NOT NULL,
	[Nazev] varchar(30) NOT NULL
)
GO

CREATE TABLE [Sklad]
(
	[SkladID] int IDENTITY(1,1) NOT NULL,
	[AdresaID] int NOT NULL,
	[SkladovaKapacita] int NOT NULL,
	[TelefonniCislo] varchar(30) NOT NULL
)
GO

CREATE TABLE [Zamestnanec]
(
	[ZamestnanecID] int IDENTITY(1,1) NOT NULL,
	[OddeleniID] int NOT NULL,
	[Titul] varchar(20) NULL,
	[Jmeno] varchar(100) NOT NULL,
	[Prijmeni] varchar(100) NOT NULL,
	[UzivatelskeJmeno] varchar(200) NOT NULL,
	[Plat] int NOT NULL,
	[ProcentoProdeje] float NULL,
	[DatumZahajeni] date NOT NULL
)
GO

CREATE TABLE [Zbozi]
(
	[ZboziID] int IDENTITY(1,1) NOT NULL,
	[ProduktovaRadaID] int NULL,
	[SkladID] int NOT NULL,
	[CenaDoporucena] int NOT NULL,
	[Mena] varchar(20) NOT NULL,
	[Nazev] varchar(50) NOT NULL,
	[Mnozstvi] int NOT NULL,
	[Jednotka] varchar(20) NULL,
	[Popis] varchar(100) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Adresa] 
 ADD CONSTRAINT [PK_Adresa]
	PRIMARY KEY CLUSTERED ([AdresaID] ASC)
GO

ALTER TABLE [Klient] 
 ADD CONSTRAINT [PK_Klient]
	PRIMARY KEY CLUSTERED ([KlientID] ASC)
GO

ALTER TABLE [Objednavka] 
 ADD CONSTRAINT [PK_Objednavka]
	PRIMARY KEY CLUSTERED ([ObjednavkaID] ASC)
GO

ALTER TABLE [Oddeleni] 
 ADD CONSTRAINT [PK_Oddeleni]
	PRIMARY KEY CLUSTERED ([OddeleniID] ASC)
GO

ALTER TABLE [ProduktovaRada] 
 ADD CONSTRAINT [PK_ProduktovaRada]
	PRIMARY KEY CLUSTERED ([ProduktovaRadaID] ASC)
GO

ALTER TABLE [RadekObjednavky] 
 ADD CONSTRAINT [PK_RadekObjednavky]
	PRIMARY KEY CLUSTERED ([RadekObjednavkyID] ASC)
GO

ALTER TABLE [Region] 
 ADD CONSTRAINT [PK_Region]
	PRIMARY KEY CLUSTERED ([RegionID] ASC)
GO

ALTER TABLE [Sklad] 
 ADD CONSTRAINT [PK_Sklad]
	PRIMARY KEY CLUSTERED ([SkladID] ASC)
GO

ALTER TABLE [Zamestnanec] 
 ADD CONSTRAINT [PK_Zamestnanec]
	PRIMARY KEY CLUSTERED ([ZamestnanecID] ASC)
GO

ALTER TABLE [Zbozi] 
 ADD CONSTRAINT [PK_Zbozi]
	PRIMARY KEY CLUSTERED ([ZboziID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Adresa] ADD CONSTRAINT [FK_Adresa_Region]
	FOREIGN KEY ([RegionID]) REFERENCES [Region] ([RegionID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_Adresa]
	FOREIGN KEY ([AdresaID]) REFERENCES [Adresa] ([AdresaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Objednavka] ADD CONSTRAINT [FK_Objednavka_Adresa_D]
	FOREIGN KEY ([DodaciAdresa]) REFERENCES [Adresa] ([AdresaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Objednavka] ADD CONSTRAINT [FK_Objednavka_Klient]
	FOREIGN KEY ([KlientID]) REFERENCES [Klient] ([KlientID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Objednavka] ADD CONSTRAINT [FK_Objednavka_Zamestnanec]
	FOREIGN KEY ([ZamestnanecID]) REFERENCES [Zamestnanec] ([ZamestnanecID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Objednavka] ADD CONSTRAINT [FK_Objednavka_Adresa_F]
	FOREIGN KEY ([FakturacniAdresa]) REFERENCES [Adresa] ([AdresaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [RadekObjednavky] ADD CONSTRAINT [FK_RadekObjednavky_Zbozi]
	FOREIGN KEY ([ZboziID]) REFERENCES [Zbozi] ([ZboziID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [RadekObjednavky] ADD CONSTRAINT [FK_RadekObjednavky_Objednavka]
	FOREIGN KEY ([ObjednavkaID]) REFERENCES [Objednavka] ([ObjednavkaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Sklad] ADD CONSTRAINT [FK_Sklad_Adresa]
	FOREIGN KEY ([AdresaID]) REFERENCES [Adresa] ([AdresaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zamestnanec] ADD CONSTRAINT [FK_Zamestnanec_Oddeleni]
	FOREIGN KEY ([OddeleniID]) REFERENCES [Oddeleni] ([OddeleniID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zbozi] ADD CONSTRAINT [FK_Zbozi_ProduktovaRada]
	FOREIGN KEY ([ProduktovaRadaID]) REFERENCES [ProduktovaRada] ([ProduktovaRadaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zbozi] ADD CONSTRAINT [FK_Zbozi_Sklad]
	FOREIGN KEY ([SkladID]) REFERENCES [Sklad] ([SkladID]) ON DELETE No Action ON UPDATE No Action
GO
